### ISSUE TITLE
M1 Macbook Air base model, not injecting due to osxinj not working on big sur

### ISSUE THREAD

**Issue by Hydrogen37** [Lyceion/ButOSX#31]

**Comment by Lyceion** [comment]
I'm using osxinj on big sur without any problem.

**Comment by Hydrogen37** [comment]
@Lyceion do you have a version of osxinj that you can send me that I can use?

**Comment by Lyceion** [comment]
> @Lyceion update for m1 pls

Already works for m1. (if you have a m1 injector which doesn't about me)

WORKS ON M1 IF YOU HAVE INJECTOR WHICH I DONT PROVIDE

Proof from discord:
![AFE1A657-FE87-4A71-9D2D-3988CA3B5A0A](https://user-images.githubusercontent.com/21990827/134226647-1a0818f1-3786-4965-b450-b9cfcac90d1e.jpeg)

(Censored bc i'm sharing screenshot without their permission. I'm not sure they want to expose theirselfs.)

**Comment by Lyceion** [comment]
> @Lyceion update for m1 pls

Already works for m1. (if you have a m1 injector which doesn't about me)

WORKS ON M1 IF YOU HAVE INJECTOR WHICH I DONT PROVIDE

Proof from discord:
![DE91A836-9E78-45A9-81B3-9A5D99F68BCE](https://user-images.githubusercontent.com/21990827/134227148-50761cbb-1fdc-4959-8644-4db5660f8799.jpeg)


(Censored bc i'm sharing screenshot without their permission. I'm not sure they want to expose theirselfs.)

**Comment by imdecoder** [comment]
can you share discord channel? @Lyceion

**Comment by Lyceion** [comment]
> can you share discord channel? @Lyceion

Not public anymore. Sorry... But you can search other injectors which doesn't use process hjacking method can probably inject.

**Comment by imdecoder** [comment]
> > can you share discord channel? @Lyceion
> 
> Not public anymore. Sorry... But you can search other injectors which doesn't use process hjacking method can probably inject. (Which the method osxinj uses.)

Thanks man, i search "libButOSX.dylib" file can you send me? 😅

**Comment by Lyceion** [comment]
> > > can you share discord channel? @Lyceion
> > 
> > 
> > Not public anymore. Sorry... But you can search other injectors which doesn't use process hjacking method can probably inject. (Which the method osxinj uses.)
> 
> Thanks man, i search "libButOSX.dylib" file can you send me? 😅

Removed from github because of uc rules. If you have uc account you can download from https://www.unknowncheats.me/forum/downloads.php?do=file&id=33979 . If you don't, mail me from lyceion@protonmail.com i'm gonna send you one when i arrive home. Also you can speak Turkish. I'm also Turkish.

**Comment by TheArmKing** [comment]
You can refer to this: aixxe.net/2016/09/shared-library-injection

**Comment by imdecoder** [comment]
This is for linux only @TheArmKing

**Comment by TheArmKing** [comment]
> This is for linux only @TheArmKing

With a few adjustments it can be made to work on macOS as well. You will need lldb instead of gdb

**Comment by Hydrogen37** [comment]
when I try to compile osxinj in xcode, it gives 2 errors:
Architecture not supported
Implicit declaration of function 'close' is invalid in C99
Using M1 Macbook Air

**Comment by imdecoder** [comment]
I fixed "**Implicit declaration of function 'close' is invalid in C99**" problem. @Hydrogen37 @Lyceion @TheArmKing 
You need to include a library at the top of the **mach_inject file**.

Add `#include <unistd.h> // for close` after `#include <fcntl.h> // for open`  code.
However, there is still "**Architecture not supported**" error.

**Comment by imdecoder** [comment]
@Lyceion Hocam M1'de çalışan injectoru buldum. Ancak şimdide "libButOSX.dylib" çalışmıyor.

**Comment by Hydrogen37** [comment]
> I fixed "**Implicit declaration of function 'close' is invalid in C99**" problem. @Hydrogen37 @Lyceion @TheArmKing
> You need to include a library at the top of the **mach_inject file**.
> 
> Add `#include <unistd.h> // for close` after `#include <fcntl.h> // for open` code.
> However, there is still "**Architecture not supported**" error.

did what you said, indeed fixed the C99 problem. Architecture not supported problem still unable to fix. @Lyceion

**Comment by TheArmKing** [comment]
Fixing the `C99` issue on `osxinj` won't help. However, this alternate method can be used to inject on M1 (via `Terminal` with `lldb` installed):
```bash
#thanks to aixxe.net/2016/09/shared-library-injection
sudo lldb --batch \
  -o "attach --name csgo_osx64" \
  -o "expr void* \$library = (void*)dlopen(\"/path/to/cheat.dylib\", 10)" \
  -o "detach" \
  -o "quit"
  ```
  Taken from https://github.com/fakePh0e/osxGlow/blob/main/load.command

**Comment by imdecoder** [comment]
`ButOSX` does not work with this injector :(

**Comment by TheArmKing** [comment]
> `ButOSX` does not work with this injector :(

It will. Make sure you are running it correctly - the path to the dylib is correct and that the dylib is x86_64, not arm64.

**Comment by Garsiya777** [comment]
> > @Lyceion update for m1 pls
> 
> 
> 
> Already works for m1. (if you have a m1 injector which doesn't about me)
> 
> 
> 
> WORKS ON M1 IF YOU HAVE INJECTOR WHICH I DONT PROVIDE
> 
> 
> 
> Proof from discord:
> 
> ![DE91A836-9E78-45A9-81B3-9A5D99F68BCE](https://user-images.githubusercontent.com/21990827/134227148-50761cbb-1fdc-4959-8644-4db5660f8799.jpeg)
> 
> 
> 
> 
> 
> (Censored bc i'm sharing screenshot without their permission. I'm not sure they want to expose theirselfs.)

HI, please help me with the injection on m1

**Comment by antofung** [comment]
it freezes upon injection for m1 Mac using fakePh0e injector

**Comment by antofung** [comment]
<img width="1267" alt="Screen Shot 2022-08-29 at 12 48 41 am" src="https://user-images.githubusercontent.com/45930441/187080121-1805f676-f822-4f5e-bf13-38f89efb49f8.png">


<img width="1266" alt="Screen Shot 2022-08-29 at 12 48 46 am" src="https://user-images.githubusercontent.com/45930441/187080132-9bddeb0a-8ee7-4ae3-82ad-8c08edf35d41.png">

injection now works but crashes here. see the debug

**Comment by kotleni** [comment]
> 

Thx, you ✅🤗

**Comment by kotleni** [comment]
And you can use this project: https://github.com/kotleni-reverse/csgo-run.

It's just support libs injecting.

**Comment by kotleni** [comment]
> > And you can use this project: https://github.com/kotleni-reverse/csgo-run.
> > It's just support libs injecting.
> 
> Hi @kotleni . I went to the project you linked, but was unable to figure out how to make it work. I downloaded the zip file, and then copy and pasted the Makefile code for OSX in terminal. This process was successful as it made the csgo_osx64 Unix Executable File. However, I started experiencing issues from this point forward. I don't know how to inject this file at all. I have read the readme.md file given and tried many different injecting options as well, but I feel like I am doing it wrong. Can you please tell me what I need to write in terminal so that I can inject the file? Thank you so much.

You can replace original file csgo_osx64 in csgo game directory (Like: Steam -> CSGO -> Settings -> Additional -> Open game directory). **And you can see it video: https://youtu.be/NVNAeQIqQIo**

**Comment by kotleni** [comment]
> > > > And you can use this project: https://github.com/kotleni-reverse/csgo-run.
> 
> > > > It's just support libs injecting.
> 
> > > 
> 
> > > 
> 
> > > Hi @kotleni . I went to the project you linked, but was unable to figure out how to make it work. I downloaded the zip file, and then copy and pasted the Makefile code for OSX in terminal. This process was successful as it made the csgo_osx64 Unix Executable File. However, I started experiencing issues from this point forward. I don't know how to inject this file at all. I have read the readme.md file given and tried many different injecting options as well, but I feel like I am doing it wrong. Can you please tell me what I need to write in terminal so that I can inject the file? Thank you so much.
> 
> > 
> 
> > 1. You can replace original file csgo_osx64 in csgo game directory (Like: Steam -> CSGO -> Game settings (Gear icon) -> Additional -> Open game directory).
> 
> > 2. Set game custom command line arguments to `-inj <lib> -injdelay <secs>` (recommended 70 secs). (Like: Steam -> CSGO -> Game settings (Gear icon) -> General -> Command line arguments)
> 
> > 
> 
> > **And you can see it video: https://youtu.be/NVNAeQIqQIo**
> 
> 
> 
> @kotleni Wow, ok got it thank you so much. I just want to ensure that replacing the original file will not cause a ban. I have 3 more questions for you. 
> 
> 
> 
> 1. Is there a way to inject without replacing the original file like the ButOSX dylib but with the original game file?
> 
> 
> 
> 2. Also, where did you get the ButOSX dylib file? Can you send it to me, please?
> 
> 
> 
> 3. I have been using fakePh0e injector, which has been working so far as a simple glow hack, but after the new CS:GO update a couple of days ago, I can still inject without any issues, but the glow hack doesn't work. Is there a way this can be updated, perhaps?
> 
> 
> 
> Thank you once again.

I used this modified file, and I didn't get banned. And all custom external injectors is broken now on MacOS.

It's works for me now, after game updating. 👀

**Comment by kotleni** [comment]
> > > > > > And you can use this project: https://github.com/kotleni-reverse/csgo-run.
> 
> > > 
> 
> > > 
> 
> > > > > > It's just support libs injecting.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Hi @kotleni . I went to the project you linked, but was unable to figure out how to make it work. I downloaded the zip file, and then copy and pasted the Makefile code for OSX in terminal. This process was successful as it made the csgo_osx64 Unix Executable File. However, I started experiencing issues from this point forward. I don't know how to inject this file at all. I have read the readme.md file given and tried many different injecting options as well, but I feel like I am doing it wrong. Can you please tell me what I need to write in terminal so that I can inject the file? Thank you so much.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 1. You can replace original file csgo_osx64 in csgo game directory (Like: Steam -> CSGO -> Game settings (Gear icon) -> Additional -> Open game directory).
> 
> > > 
> 
> > > 
> 
> > > > 2. Set game custom command line arguments to `-inj <lib> -injdelay <secs>` (recommended 70 secs). (Like: Steam -> CSGO -> Game settings (Gear icon) -> General -> Command line arguments)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > **And you can see it video: https://youtu.be/NVNAeQIqQIo**
> 
> > > 
> 
> > > 
> 
> > > @kotleni Wow, ok got it thank you so much. I just want to ensure that replacing the original file will not cause a ban. I have 3 more questions for you.
> 
> > > 
> 
> > > 1. Is there a way to inject without replacing the original file like the ButOSX dylib but with the original game file?
> 
> > > 2. Also, where did you get the ButOSX dylib file? Can you send it to me, please?
> 
> > > 3. I have been using fakePh0e injector, which has been working so far as a simple glow hack, but after the new CS:GO update a couple of days ago, I can still inject without any issues, but the glow hack doesn't work. Is there a way this can be updated, perhaps?
> 
> > > 
> 
> > > Thank you once again.
> 
> > 
> 
> > I used this modified file, and I didn't get banned. And all custom external injectors is broken now on MacOS.
> 
> > 
> 
> > It's works for me now, after game updating. 👀
> 
> 
> 
> @kotleni Ok understood, thank you. Can you please give me the libButOSX.dylib file as I do not have it but I saw you have it on your computer so I can work this? Thank you so much once again.

Yes, you have Telegram/Discord/Twitter?

**Comment by kotleni** [comment]
> > > > > > > > And you can use this project: https://github.com/kotleni-reverse/csgo-run.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > It's just support libs injecting.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > Hi @kotleni . I went to the project you linked, but was unable to figure out how to make it work. I downloaded the zip file, and then copy and pasted the Makefile code for OSX in terminal. This process was successful as it made the csgo_osx64 Unix Executable File. However, I started experiencing issues from this point forward. I don't know how to inject this file at all. I have read the readme.md file given and tried many different injecting options as well, but I feel like I am doing it wrong. Can you please tell me what I need to write in terminal so that I can inject the file? Thank you so much.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 1. You can replace original file csgo_osx64 in csgo game directory (Like: Steam -> CSGO -> Game settings (Gear icon) -> Additional -> Open game directory).
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 2. Set game custom command line arguments to `-inj <lib> -injdelay <secs>` (recommended 70 secs). (Like: Steam -> CSGO -> Game settings (Gear icon) -> General -> Command line arguments)
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > **And you can see it video: https://youtu.be/NVNAeQIqQIo**
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > @kotleni Wow, ok got it thank you so much. I just want to ensure that replacing the original file will not cause a ban. I have 3 more questions for you.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 1. Is there a way to inject without replacing the original file like the ButOSX dylib but with the original game file?
> 
> > > 
> 
> > > 
> 
> > > > > 2. Also, where did you get the ButOSX dylib file? Can you send it to me, please?
> 
> > > 
> 
> > > 
> 
> > > > > 3. I have been using fakePh0e injector, which has been working so far as a simple glow hack, but after the new CS:GO update a couple of days ago, I can still inject without any issues, but the glow hack doesn't work. Is there a way this can be updated, perhaps?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Thank you once again.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I used this modified file, and I didn't get banned. And all custom external injectors is broken now on MacOS.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > It's works for me now, after game updating. 👀
> 
> > > 
> 
> > > 
> 
> > > @kotleni Ok understood, thank you. Can you please give me the libButOSX.dylib file as I do not have it but I saw you have it on your computer so I can work this? Thank you so much once again.
> 
> > 
> 
> > Yes, you have Telegram/Discord/Twitter?
> 
> 
> 
> Yes, my discord is dexator5#3108
> 
> 
> 
> Thank you so much once again bro I really appreciate it!

Sorry, i can't find you in Discord. 
Text me: kotleni#7119

**Comment by PHILKAULTRA** [comment]
> Fixing the `C99` issue on `osxinj` won't help. However, this alternate method can be used to inject on M1 (via `Terminal` with `lldb` installed):
> 
> ```shell
> #thanks to aixxe.net/2016/09/shared-library-injection
> sudo lldb --batch \
>   -o "attach --name csgo_osx64" \
>   -o "expr void* \$library = (void*)dlopen(\"/path/to/cheat.dylib\", 10)" \
>   -o "detach" \
>   -o "quit"
> ```
> 
> Taken from https://github.com/fakePh0e/osxGlow/blob/main/load.command

I have this error - error: attach failed: more than one process named csgo_osx64:

**Comment by katanapiggy** [comment]
hi, i downloaded everything needed, i put it into the launch preferences and when i click play, with turns blue and says stop. it stays stuck, and i have to forcequit to rejoin
